### ISSUE TITLE
The model files are deleted

### ISSUE THREAD

**Issue by datavistics** [leonardtang/The-Naughtyformer#2]
It looks like you deleted the model files: https://github.com/leonardtang/The-Naughtyformer/commit/b0f0b3419b986b9a7c375140ea0e41e8ade810e8

**Comment by leonardtang** [comment]
Yup, they're now at a [Drive link](https://drive.google.com/file/d/15YMRcMT3JsXXKBmFx7jFfQS6om0Kfs-x/view?usp=sharing)!

**Comment by datavistics** [comment]
Yeah, it works now thanks!
